name:                mtaylor-io-events-client
version:             0.1.0.0
github:              "mtaylor91/events-client"
license:             BSD-3-Clause
author:              "Mike Taylor"
maintainer:          "mike.charles.taylor@gmail.com"
copyright:           "Copyright (c) 2024"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mtaylor91/events-client#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- http-client
- http-client-tls
- mtaylor-io-iam-client
- mtaylor-io-iam-core
- mtaylor-io-events-core
- servant-client
- servant-server
- stm
- text
- uuid

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  events-client-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mtaylor-io-events-client

tests:
  events-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mtaylor-io-events-client
